services:
  app:
    image: user-management-backend:0.0.1
    container_name: user-management-app
    build:
      context: .
    ports:
      - ${SERVER_PORT}:8080
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - user-management-network

  db:
    image: postgres:16.8-alpine3.20
    container_name: db_user-management
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data_user-management:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - user-management-network

networks:
  user-management-network:

volumes:
  pg_data_user-management: